### PR TITLE
Add support for loading edn namespaced maps

### PR DESCRIPTION
**Pull request by bhagany**
Addresses #16 and implements loading edn with namespaced maps

### CODE REVIEW

**Comment by bhagany** [comment]
I added a test, but there are several unrelated tests that don't pass on python 2.7.8 with a clean checkout

**Comment by sunng87** [comment]
Thank you @bhagany! I will look into those failures later today.

**Comment by sunng87** [comment]
Tested from my local python 2.7.12, all tests passed.

**Comment by bhagany** [comment]
Excellent, thanks for the quick merge!

**Pull request merged**
